// This file is auto-generated by @hey-api/openapi-ts

export type UserDto = {
    id?: number;
    username?: string;
    email?: string;
    phone?: string;
    password?: string;
    deptId?: number;
};

export type ResultInteger = {
    code?: number;
    message?: string;
    data?: number;
    success?: boolean;
};

export type ResultUserVo = {
    code?: number;
    message?: string;
    data?: UserVo;
    success?: boolean;
};

export type UserVo = {
    id?: number;
    username?: string;
    email?: string;
    phone?: string;
};

export type CreateUserData = {
    body: UserDto;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type CreateUserResponses = {
    /**
     * OK
     */
    200: ResultInteger;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type EditUserData = {
    body: UserDto;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type EditUserResponses = {
    /**
     * OK
     */
    200: number;
};

export type EditUserResponse = EditUserResponses[keyof EditUserResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type DeleteUserResponses = {
    /**
     * OK
     */
    200: number;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type GetUserByIdResponses = {
    /**
     * OK
     */
    200: ResultUserVo;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:8080' | (string & {});
};