// This file is auto-generated by @hey-api/openapi-ts

export type UserDto = {
    id?: number;
    username?: string;
    email?: string;
    phone?: string;
    password?: string;
    deptId?: number;
};

export type ResultInteger = {
    code?: number;
    message?: string;
    data?: number;
    success?: boolean;
};

export type LoginDto = {
    username?: string;
    password?: string;
};

export type ResultLoginDto = {
    code?: number;
    message?: string;
    data?: LoginDto;
    success?: boolean;
};

export type LoginVo = {
    token?: string;
    username?: string;
};

export type ResultLoginVo = {
    code?: number;
    message?: string;
    data?: LoginVo;
    success?: boolean;
};

export type ResultUserVo = {
    code?: number;
    message?: string;
    data?: UserVo;
    success?: boolean;
};

export type UserVo = {
    id?: number;
    username?: string;
    email?: string;
    phone?: string;
};

export type CreateUserData = {
    body: UserDto;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type CreateUserResponses = {
    /**
     * OK
     */
    200: ResultInteger;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type EditUserData = {
    body: UserDto;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type EditUserResponses = {
    /**
     * OK
     */
    200: number;
};

export type EditUserResponse = EditUserResponses[keyof EditUserResponses];

export type RegisterData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/api/register';
};

export type RegisterResponses = {
    /**
     * OK
     */
    200: ResultLoginDto;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/api/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: ResultLoginVo;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LoginOrRegisterData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/api/loginOrRegister';
};

export type LoginOrRegisterResponses = {
    /**
     * OK
     */
    200: ResultLoginVo;
};

export type LoginOrRegisterResponse = LoginOrRegisterResponses[keyof LoginOrRegisterResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type DeleteUserResponses = {
    /**
     * OK
     */
    200: number;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type GetUserByIdResponses = {
    /**
     * OK
     */
    200: ResultUserVo;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:8080' | (string & {});
};