// This file is auto-generated by @hey-api/openapi-ts

export type UserDto = {
    id?: number;
    username?: string;
    email?: string;
    phone?: string;
    password?: string;
    deptId?: number;
};

export type Menu = {
    id?: number;
    createTime?: number;
    updateTime?: number;
    name?: string;
    path?: string;
    icon?: string;
    status?: number;
    parentId?: number;
    sortNum?: number;
    children?: Array<Menu>;
};

export type ResultLong = {
    code?: number;
    message?: string;
    data?: number;
    success?: boolean;
};

export type ResultInteger = {
    code?: number;
    message?: string;
    data?: number;
    success?: boolean;
};

export type LoginDto = {
    username?: string;
    password?: string;
};

export type ResultLoginDto = {
    code?: number;
    message?: string;
    data?: LoginDto;
    success?: boolean;
};

export type MenuQuery = {
    current?: number;
    pageSize?: number;
    name?: string;
    path?: string;
    status?: number;
    parentId?: number;
};

export type IPageMenu = {
    size?: number;
    current?: number;
    total?: number;
    records?: Array<Menu>;
    /**
     * @deprecated
     */
    pages?: number;
};

export type ResultIPageMenu = {
    code?: number;
    message?: string;
    data?: IPageMenu;
    success?: boolean;
};

export type ResultUserVo = {
    code?: number;
    message?: string;
    data?: UserVo;
    success?: boolean;
};

export type UserVo = {
    id?: number;
    username?: string;
    email?: string;
    phone?: string;
};

export type ResultMenu = {
    code?: number;
    message?: string;
    data?: Menu;
    success?: boolean;
};

export type IdsDto = {
    ids?: Array<number>;
};

export type CreateUserData = {
    body: UserDto;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type CreateUserResponses = {
    /**
     * OK
     */
    200: ResultInteger;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type EditUserData = {
    body: UserDto;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type EditUserResponses = {
    /**
     * OK
     */
    200: number;
};

export type EditUserResponse = EditUserResponses[keyof EditUserResponses];

export type DelMenuData = {
    body: IdsDto;
    path?: never;
    query?: never;
    url: '/api/menu';
};

export type DelMenuResponses = {
    /**
     * OK
     */
    200: ResultInteger;
};

export type DelMenuResponse = DelMenuResponses[keyof DelMenuResponses];

export type CreateMenuData = {
    body: Menu;
    path?: never;
    query?: never;
    url: '/api/menu';
};

export type CreateMenuResponses = {
    /**
     * OK
     */
    200: ResultLong;
};

export type CreateMenuResponse = CreateMenuResponses[keyof CreateMenuResponses];

export type EditMenuData = {
    body: Menu;
    path?: never;
    query?: never;
    url: '/api/menu';
};

export type EditMenuResponses = {
    /**
     * OK
     */
    200: ResultLong;
};

export type EditMenuResponse = EditMenuResponses[keyof EditMenuResponses];

export type RegisterData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/api/register';
};

export type RegisterResponses = {
    /**
     * OK
     */
    200: ResultLoginDto;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type GetMenusData = {
    body: MenuQuery;
    path?: never;
    query?: never;
    url: '/api/menu/list';
};

export type GetMenusResponses = {
    /**
     * OK
     */
    200: ResultIPageMenu;
};

export type GetMenusResponse = GetMenusResponses[keyof GetMenusResponses];

export type LoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/api/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: ResultUserVo;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LoginOrRegisterData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/api/loginOrRegister';
};

export type LoginOrRegisterResponses = {
    /**
     * OK
     */
    200: ResultUserVo;
};

export type LoginOrRegisterResponse = LoginOrRegisterResponses[keyof LoginOrRegisterResponses];

export type CheckAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/checkAuth';
};

export type CheckAuthResponses = {
    /**
     * OK
     */
    200: ResultUserVo;
};

export type CheckAuthResponse = CheckAuthResponses[keyof CheckAuthResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type DeleteUserResponses = {
    /**
     * OK
     */
    200: number;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type GetUserByIdResponses = {
    /**
     * OK
     */
    200: ResultUserVo;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type GetMenuData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/menu/{id}';
};

export type GetMenuResponses = {
    /**
     * OK
     */
    200: ResultMenu;
};

export type GetMenuResponse = GetMenuResponses[keyof GetMenuResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:8080' | (string & {});
};